config/routes.rb
Rails.application.routes.draw do
  resources :pages

  root to: 'pages#index'
  get '/signup' => 'pages#signupform' 
  get '/brands' => 'pages#brands'
  get '/editaccount' => 'pages#editaccount'
  get '/editprofile'=> 'pages#editprofile'
  get '/faq' => 'pages#faq'
  get '/proposals'=> 'pages#proposals'
  get '/profile'=> 'pages#profile'
  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  def editaccount
  end

  def editprofile
  end

def brands
end

  def faq
  end

  def proposals
  end
  
  def profile
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


def signupform
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="" />
<title>capish</title>


  <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %> !-->
  <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 
  <%= csrf_meta_tags %>



</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/about.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="" />
<title>capish</title>
<link rel="stylesheet" type="text/css" href="assets/bootstrap.css">
<link href="assets/style.css" rel="stylesheet" type="text/css"  media="all"  />
<script src="assets/jquery-1.12.0.min.js" type="text/javascript"></script>
<script src="assets/bootstrap.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="assets/bootstrap-select.min.css">
<script src="assets/bootstrap-select.js"></script>
</head>
<body>

<div class="row row0">
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" title="capish">capish</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Proposals<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Messages<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Brands</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="btn4">salimbugay</a></li>
        <li><a href="#" class="btn1"><i class="fa fa-cog"></i>&nbsp;Edit Profile</a></li>
        <li><a href="#" class="btn2"><i class="fa fa-question-circle"></i>&nbsp;FAQ</a></li>
        <li><a href="#" class="btn3"><i class="fa fa-sign-out"></i>&nbsp;Sign-out</a></li>
      </ul>
    </div>
  </div>
</nav>
</header>
</div>


<div class="txtpage">
<div class="container">
<h2 class="text-center">ABOUT</h2>
 
<div class="text-center"><img width="400" src="assets/office.png" /></div>
<br /><br />
AN ONLINE COMMUNITY BUILT FOR YOU
<br /><br />
At Capish, we're building a community that values the creative talent of Instagrammers like you. We are driven by a simple mission, to support the most talented Instagrammers to focus on what they do best - sharing your passions with the world in authentic, inspiring ways. 
<br /><br />
We live in an exciting time. Our new economy has provided boundless opportunities for the creative class to make a meaningful living off their talents. We’ve created an online community built on transparency and honesty to connect top brands with the best Instagrammers. We're hoping this community will support you in taking advantage of this new economy. so you can continue creating beautiful photos that engage and inspire. 
<br /><br />
<strong>WHO WE ARE</strong>
<br /><br />
We are an innovative team of Instagrammers, marketers, coders and thought leaders. Capish was created to respond to the growing need for brands to find, partner and collaborate with Instagrammers. 
<br /><br />
<strong>A MATCH MADE IN HEAVEN</strong>
<br /><br />
We know that you as an Instagrammer would rather focus on the creative side of what you do. We've taken care of all the boring stuff so that you can focus on what you do best, and get paid for it. 
<br /><br />
Brands are always looking for new and interesting ways to tell their stories.  Instagram is an awesome way for them to tell their stories through your photo lens. You've spent years honing your craft and building your following, and brands are looking towards you to tell their stories through your eyes. But finding the right Instagrammer to tell their story in the right way can be hard to find. 
<br /><br />
Our community lets you work effortlessly with brands anywhere in the world so you can work on fun and creative campaigns that fit your passions and interests and will engage your followers. 
<br /><br />
<strong>TELL US HOW WE CAN DO BETTER</strong>
<br /><br />
If you've got any ideas on what you'd like to see or what you're looking for in such a community, please drop us a line.
<br /><br />

<div id="wufoo-z1vr8hvz18yc32c"><iframe height="345" frameborder="0" src="https://capish.wufoo.com/embed/z1vr8hvz18yc32c/def/embedKey=z1vr8hvz18yc32c727434&amp;entsource=&amp;referrer=" style="width:100%;border:none" scrolling="no" allowtransparency="true" class="wufoo-form-container" id="wufooFormz1vr8hvz18yc32c">&lt;a href="https://capish.wufoo.com/forms/z1vr8hvz18yc32c/" title="html form"&gt;Fill out my Wufoo form!&lt;/a&gt;</iframe></div>

</div>
</div>

<div class="footer-wrapper">
<div class="container text-center">
	<footer>
		<a href="#">Contact</a>
		<a href="#">FAQ</a>
		<a href="#">Privacy</a>
		<a href="#">Terms</a>
	</footer>
</div>
</div>
<script type="text/javascript">
	$('.selectpicker').selectpicker({
  size: 4
});		
</script>
</body>
</html>

app/views/pages/brands.html.erb


<div class="row row0">
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" title="capish">capish</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Proposals<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Messages<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Brands</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="btn4">salimbugay</a></li>
        <li><a href="#" class="btn1"><i class="fa fa-cog"></i>&nbsp;Edit Profile</a></li>
        <li><a href="#" class="btn2"><i class="fa fa-question-circle"></i>&nbsp;FAQ</a></li>
        <li><a href="#" class="btn3"><i class="fa fa-sign-out"></i>&nbsp;Sign-out</a></li>
      </ul>
    </div>
  </div>
</nav>
</header>
</div>


<div class="container">
<h1 class="text-center">BRANDS</h1> 
Pitch brands directly with a campaign idea.

<div class="row row0 text-center brandbox">
<div class="row masonry-container">
<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/vodafone.png" /><em>Vodafone is one of the world’s leading telecommunications groups with a significant presence in Europe and other countries.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/hepsiburada.png" /><em>Hepsiburada.com has been established as an e-commerce site aim at satisfying internet users’ needs, since 1998</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/vogue.png" /><em>Your favorite fashion, beautiy and lifestyle brands. Events, behind-the-scenes buzz and exclusive offers.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/nautica.png" /><em>Founded in 1983, Nautica has evolved from a collection of men’s outwear to a leading global lifestyle brand.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/loreal.png" /><em>The Bridgestone Group has over 180 manufacturing plants and R&D facilities in 25 countries.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/becks.png" /><em>Premium quality, light golden colour, hoppy flavour. Brewed using only natural
ingredients.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/starbucks.png" /><em>To say Starbucks purchases and roasts high quality whole bean cofees is very true. We do that.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

<div class="col-lg-4 col-md-4 col-sm-4 text-center thumb"><img class="img-responsive" src="assets/thy.png" /><em>Turkish Airlines is the national flag carrier airline of Turkey. We strive to make you happy everywhere.</em><button type="submit" class="btn btn-send">PITCH AN IDEA</button></div>

</div>
</div>

</div>

<div class="footer-wrapper">
<div class="container text-center">
	<footer>
		<a href="#">Contact</a>
		<a href="#">FAQ</a>
		<a href="#">Privacy</a>
		<a href="#">Terms</a>
	</footer>
</div>
</div>
<script type="text/javascript">
	$('.selectpicker').selectpicker({
  size: 4
});		
</script>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/editaccount.html.erb


<div class="row row0">
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" title="capish">capish</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Proposals<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Messages<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Brands</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="btn4">salimbugay</a></li>
        <li><a href="#" class="btn1"><i class="fa fa-cog"></i>&nbsp;Edit Profile</a></li>
        <li><a href="#" class="btn2"><i class="fa fa-question-circle"></i>&nbsp;FAQ</a></li>
        <li><a href="#" class="btn3"><i class="fa fa-sign-out"></i>&nbsp;Sign-out</a></li>
      </ul>
    </div>
  </div>
</nav>
</header>
</div>


<div class="signup signup2">
<div class="container">

<ul class="nav nav-pills nav-justified">
  <li><a href="#">EDIT PROFILE</a></li>
  <li class="active"><a href="#">EDIT ACCOUNT</a></li>
</ul>

 <form role="form">
 
 <div class="form-group form-groupemail">
    <input type="email" class="form-control formcapish" id="email" placeholder="kimkardashian@gmail.com" onfocus="this.placeholder = ''" onblur="this.placeholder='kimkardashian@gmail.com'" />
  </div>
	
	<label class="lblpaypal">We have partnered with PayPal for global bank transfers. <a href="#">Don't have a PayPal account?</a></label>
	<div class="form-group form-grouppaypal">
		<input type="fullname" class="form-control formcapish" id="usr" placeholder="kimkardashian@gmail.com" onfocus="this.placeholder = ''" onblur="this.placeholder='kimkardashian@gmail.com'" />
	</div>
	
	<div class="enotif">Email Notification	
	  <label><input type="checkbox" value="" checked /> Yes</label>
	  <label><input type="checkbox" value="" /> No</label>
	</div>
	
  <div class="row row0 text-right"><button type="submit" class="btn btn-send">SAVE</button></div>
  <div class="row row0 text-right terms">By clicking save, you agree to our <a href="#">terms of use</a></div>
  <div class="row row0 top-buffer70 text-left"><button type="button" class="btn btn-default btn-delete" data-toggle="modal" data-target="#myModal">DELETE ACCOUNT</button></div>
</form>

</div>
</div>

<div class="footer-wrapper">
<div class="container text-center">
	<footer>
		<a href="#">Contact</a>
		<a href="#">FAQ</a>
		<a href="#">Privacy</a>
		<a href="#">Terms</a>
	</footer>
</div>
</div>

<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content text-center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Hey!</h4>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete your Capish account?</p>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-default btn-modalyes" data-dismiss="modal">Yes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        </div>
      </div>
    </div>
  </div>
<script type="text/javascript">
	$('.selectpicker').selectpicker({
  size: 4
});		
</script>

app/views/pages/editprofile.html.erb


<div class="row row0">
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" title="capish">capish</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Proposals<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Messages<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Brands</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="btn4">salimbugay</a></li>
        <li><a href="#" class="btn1"><i class="fa fa-cog"></i>&nbsp;Edit Profile</a></li>
        <li><a href="#" class="btn2"><i class="fa fa-question-circle"></i>&nbsp;FAQ</a></li>
        <li><a href="#" class="btn3"><i class="fa fa-sign-out"></i>&nbsp;Sign-out</a></li>
      </ul>
    </div>
  </div>
</nav>
</header>
</div>


<div class="signup signup2">
<div class="container">

<ul class="nav nav-pills nav-justified">
  <li class="active"><a href="#">EDIT PROFILE</a></li>
  <li><a href="#">EDIT ACCOUNT</a></li>
</ul>

 <form role="form">
  <div class="form-group form-groupname1 pull-left">
	<input type="firstname" class="form-control formcapish" id="usr" placeholder="First Name" onfocus="this.placeholder = ''" onblur="this.placeholder='First Name'" />
	</div>
	<div class="form-group form-groupname2 pull-right">
	<input type="lastname" class="form-control formcapish" id="usr" placeholder="Last Name" onfocus="this.placeholder = ''" onblur="this.placeholder='Last Name'" />
	</div>
	
	 <div class="form-group form-grouploc error">
	<input type="fullname" class="form-control formcapish" id="usr" placeholder="Start typing a city" onfocus="this.placeholder = ''" onblur="this.placeholder='Start typing a city'" />
	</div>


	<div class="form-group form-groupcake">
	<input type="fullname" class="form-control formcapish" id="usr" placeholder="Date of birth" onfocus="this.placeholder = ''" onblur="this.placeholder='Date of birth'" />
	</div>

	<div class="form-group form-selectfull form-noborder">
	<label for="name" class="gender"><i class="fa fa-venus-mars"></i>Gender</label>
	<select class="selectpicker">
	  <option>Madam</option>
	  <option>Adam</option>
	</select>
	</div>

	
	<div class="form-group form-selectfull form-noborder error">
	<label for="name" class="gender"><i class="fa fa-hand-rock-o"></i>What passion best describes your Instagram feed?</label>
	<select class="selectpicker">
	  <option>Select</option>
	  <option>Lifestyle</option>
	  <option>Cars</option>
	</select>
	</div>
	
	<div class="form-group form-noborder form-groupbio">
		<label for="name" class="gender"><i class="fa fa-file-text"></i>Bio <span class="bioright pull-right">300</span></label>
		<textarea placeholder="Filling in your bio is a good way for brands to get to know you better. Please limit your bio to 300 characters or less." onfocus="this.placeholder = ''" onblur="this.placeholder='Filling in your bio is a good way for brands to get to know you better. Please limit your bio to 300 characters or less.'"></textarea>
	</div>
	
	<label class="lblpaypal">This is the price per post brands will see on your profile.</label>
	<div class="form-group form-groupmoney">
		<input type="fullname" class="form-control formcapish" id="usr" placeholder="$199" onfocus="this.placeholder = '$'" onblur="this.placeholder='$199'" />
	</div>
	
  <div class="row row0 text-right"><button type="submit" class="btn btn-send">SAVE</button></div>
  <div class="row row0 text-right terms">By clicking save, you agree to our <a href="#">terms of use</a></div>
</form>

</div>
</div>

<div class="footer-wrapper">
<div class="container text-center">
	<footer>
		<a href="#">Contact</a>
		<a href="#">FAQ</a>
		<a href="#">Privacy</a>
		<a href="#">Terms</a>
	</footer>
</div>
</div>
<script type="text/javascript">
	$('.selectpicker').selectpicker({
  size: 4
});		
</script>

app/views/pages/faq.html.erb
 
<body>

<div class="row row0">
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" title="capish">capish</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Proposals<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Messages<span class="notification-icon"><span class="badge">0</span></span></a></li>
        <li><a href="#">Brands</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="btn4">salimbugay</a></li>
        <li><a href="#" class="btn1"><i class="fa fa-cog"></i>&nbsp;Edit Profile</a></li>
        <li><a href="#" class="btn2"><i class="fa fa-question-circle"></i>&nbsp;FAQ</a></li>
        <li><a href="#" class="btn3"><i class="fa fa-sign-out"></i>&nbsp;Sign-out</a></li>
      </ul>
    </div>
  </div>
</nav>
</header>
</div>


<div class="txtpage">
<div class="container">
<h2 class="text-center">FAQ</h2> 
<h3>INSTAGRAMMER FAQ's</h3>
<br />
<strong>I'm logged in, now what.</strong>
<br /><br />
You are part of our limited access program. During this program, we are working with a select group of brands to find the best Instagrammers that fit their needs. If a Brand is interested in you, we will notify you via email. In the meantime, feel free to pitch an idea to one of the brands on the Brands page. This is also a chance for us to really figure out what features are most important to both you and the brands and to help us figure out how we can make  collaborating with brands an enjoyable and fun process.  If you have any thoughts or ideas, please use the feedback form on the contact page.  
<br /><br />
<strong>How will I be compensated?</strong>
<br /><br />
We will pay you via PayPal when a brand has agreed to release payment based on you successfully completing their campaign. In the meantime, make sure that your profile is connected to a PayPal account. Go to Settings and then Edit profile for more information.  
<br /><br />
Still have a question? Head over to the Contact page or email us as <a href="mailto:hi@capish.co" target="_blank">hi@capish.co</a>.  
</div>
</div>

<div class="footer-wrapper">
<div class="container text-center">
	<footer>
		<a href="#">Contact</a>
		<a href="#">FAQ</a>
		<a href="#">Privacy</a>
		<a href="#">Terms</a>
	</footer>
</div>
</div>
<script type="text/javascript">
	$('.selectpicker').selectpicker({
  size: 4
});		
</script> 

app/views/pages/index.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="" />
<title>capish</title>
<link rel="stylesheet" type="text/css" href="assets/bootstrap.css">
<link href="assets/style.css" rel="stylesheet" type="text/css" media="all" />
<script src="assets/jquery-1.12.0.min.js" type="text/javascript"></script>
<script src="assets/bootstrap.min.js" type="text/javascript"></script>
</head>
<body>
<div class="fullimg">
	<div class="container">
		<a class="logo" href="#" title="capish">capish</a>
		<h2>WELCOME!</h2>
		We’re honored and excited to have you in our community.<br /><br />
		To activate your account, we’ll need to link your instagram account to our site and complate some basic registration information so we can begin to connect you with interested brands.<br /><br />
		Let’s get started!
		<div class="row text-center">
			<a href="#" class="btn btn-welcome" role="button">CREATE ACCOUNT</a>
		</div>
	</div>
	
</div>
</body>
</html>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>